### ISSUE TITLE
fatal error: 'thrift/Thrift.h' file not found

### ISSUE THREAD

**Issue by zzl0** [xunzhang/fault-tolerance-in-action#1]
@xunzhang I encountered `fatal error: 'thrift/Thrift.h' file not found` problem, maybe the solution will be helpfull for others, so I opened this issue. If you think the problem is irrelevant to this project, feel free to close it.
## Reason

Xcode-only gcc not searching `/usr/local/lib` and `/usr/local/include`
## Solution
1. [install CLT and reinstall gcc](https://github.com/Homebrew/legacy-homebrew/issues/34461)
2. manually pass `-I/usr/local/include` and `-L/usr/local/lib`, e.g:

``` diff
@@ -8,7 +8,8 @@ BIN_DIR = $(RPC_DIR)/bin

 CXX = g++
 CXXFLAGS = -Wall -std=c++11 -DHAVE_INTTYPES_H -DHAVE_NETINET_IN_H
-CPPFLAGS = -I$(RPC_DIR)/toy_rpc/
+CPPFLAGS = -I$(RPC_DIR)/toy_rpc/ -I/usr/local/include
+LDFLAGS = -L/usr/local/lib
 LIBS = -lpthread -lthrift

 AUTOSOURCE = $(wildcard ${RPC_DIR}/toy_rpc/*.cpp)
@@ -37,10 +38,10 @@ divide.o: ${TOY_DIR}/divide.cpp
        $(CXX) $(CPPFLAGS) $(CXXFLAGS) -c $(TOY_DIR)/divide.cpp

 toy_server: $(SERVERSOURCE)
-       $(CXX) $(CPPFLAGS) $(CXXFLAGS) ${OBJS} -o $(BIN_DIR)/toy_server $^ $(LIBS)
+       $(CXX) $(CPPFLAGS) $(CXXFLAGS) ${OBJS} -o $(BIN_DIR)/toy_server $^ $(LDFLAGS) $(LIBS)

 toy_client: $(CLIENTSOURCE)
-       $(CXX) $(CPPFLAGS) $(CXXFLAGS) ${OBJS} -o $(BIN_DIR)/toy_client $^ $(LIBS)
+       $(CXX) $(CPPFLAGS) $(CXXFLAGS) ${OBJS} -o $(BIN_DIR)/toy_client $^ $(LDFLAGS) $(LIBS)

 .PHONY: clean
```

**Comment by xunzhang** [comment]
It is right, could you send a pull request instead? Since to fix this, we can also export environment variable outside before `make`, I advice to use `+=` to make `Makefile` much more readable.

**Comment by zzl0** [comment]
OK

**Comment by zzl0** [comment]
https://github.com/xunzhang/fault-tolerance-in-action/pull/2
